import { AccountType } from "@/@Types/challenges";

export const CHALLENGES: AccountType[] = [
  {
    accountType: "evaluation",
    accountSizes: [
      {
        size: "$5k",
        registrationFee: "$45",
        tradingChallenge: {
          profitTarget: "7%",
          dailyDrawdown: "5%",
          totalDrawdown: "9%",
          timeLimit: "Zero Limit",
          payout: "80/20",
          salaryPerMonth: "0.5%",
        },
        verification: {
          profitTarget: "5%",
          dailyDrawdown: "5%",
          totalDrawdown: "9%",
          timeLimit: "Zero Limit",
          payout: "80/20",
          salaryPerMonth: "0.5%",
        },
      },
      {
        size: "$10k",
        registrationFee: "$85",
        tradingChallenge: {
          profitTarget: "7%",
          dailyDrawdown: "5%",
          totalDrawdown: "9%",
          timeLimit: "Zero Limit",
          payout: "80/20",
          salaryPerMonth: "0.5%",
        },
        verification: {
          profitTarget: "5%",
          dailyDrawdown: "5%",
          totalDrawdown: "9%",
          timeLimit: "Zero Limit",
          payout: "80/20",
          salaryPerMonth: "0.5%",
        },
      },
      {
        size: "$25k",
        registrationFee: "$190",
        tradingChallenge: {
          profitTarget: "7%",
          dailyDrawdown: "5%",
          totalDrawdown: "9%",
          timeLimit: "Zero Limit",
          payout: "80/20",
          salaryPerMonth: "0.5%",
        },
        verification: {
          profitTarget: "5%",
          dailyDrawdown: "5%",
          totalDrawdown: "9%",
          timeLimit: "Zero Limit",
          payout: "80/20",
          salaryPerMonth: "0.5%",
        },
      },
      {
        size: "$50k",
        registrationFee: "$310",
        tradingChallenge: {
          profitTarget: "7%",
          dailyDrawdown: "5%",
          totalDrawdown: "9%",
          timeLimit: "Zero Limit",
          payout: "80/20",
          salaryPerMonth: "0.5%",
        },
        verification: {
          profitTarget: "5%",
          dailyDrawdown: "5%",
          totalDrawdown: "9%",
          timeLimit: "Zero Limit",
          payout: "80/20",
          salaryPerMonth: "0.5%",
        },
      },
      {
        size: "$100k",
        registrationFee: "$480",
        tradingChallenge: {
          profitTarget: "7%",
          dailyDrawdown: "5%",
          totalDrawdown: "9%",
          timeLimit: "Zero Limit",
          payout: "80/20",
          salaryPerMonth: "0.5%",
        },
        verification: {
          profitTarget: "5%",
          dailyDrawdown: "5%",
          totalDrawdown: "9%",
          timeLimit: "Zero Limit",
          payout: "80/20",
          salaryPerMonth: "0.5%",
        },
      },
      {
        size: "$200k",
        registrationFee: "$850",
        tradingChallenge: {
          profitTarget: "7%",
          dailyDrawdown: "5%",
          totalDrawdown: "9%",
          timeLimit: "Zero Limit",
          payout: "80/20",
          salaryPerMonth: "0.5%",
        },
        verification: {
          profitTarget: "5%",
          dailyDrawdown: "5%",
          totalDrawdown: "9%",
          timeLimit: "Zero Limit",
          payout: "80/20",
          salaryPerMonth: "0.5%",
        },
      },
      {
        size: "$300k",
        registrationFee: "$1450",
        tradingChallenge: {
          profitTarget: "7%",
          dailyDrawdown: "5%",
          totalDrawdown: "9%",
          timeLimit: "Zero Limit",
          payout: "80/20",
          salaryPerMonth: "0.5%",
        },
        verification: {
          profitTarget: "5%",
          dailyDrawdown: "5%",
          totalDrawdown: "9%",
          timeLimit: "Zero Limit",
          payout: "80/20",
          salaryPerMonth: "0.5%",
        },
      },
    ],
  },
  {
    accountType: "express",
    accountSizes: [
      {
        size: "$5k",
        registrationFee: "$200",
        tradingChallenge: {
          profitTarget: "none",
          dailyDrawdown: "5%",
          totalDrawdown: "6%",
          timeLimit: "Zero Limit",
        },
      },
      {
        size: "$10k",
        registrationFee: "$400",
        tradingChallenge: {
          profitTarget: "none",
          dailyDrawdown: "5%",
          totalDrawdown: "6%",
          timeLimit: "Zero Limit",
        },
      },
      {
        size: "$25k",
        registrationFee: "$850",
        tradingChallenge: {
          profitTarget: "none",
          dailyDrawdown: "5%",
          totalDrawdown: "6%",
          timeLimit: "Zero Limit",
        },
      },
      {
        size: "$50k",
        registrationFee: "$1900",
        tradingChallenge: {
          profitTarget: "none",
          dailyDrawdown: "5%",
          totalDrawdown: "6%",
          timeLimit: "Zero Limit",
        },
      },
      {
        size: "$100k",
        registrationFee: "$3800",
        tradingChallenge: {
          profitTarget: "none",
          dailyDrawdown: "5%",
          totalDrawdown: "6%",
          timeLimit: "Zero Limit",
        },
      },
      {
        size: "$200k",
        registrationFee: "$7200",
        tradingChallenge: {
          profitTarget: "none",
          dailyDrawdown: "5%",
          totalDrawdown: "6%",
          timeLimit: "Zero Limit",
        },
      },
    ],
  },
  {
    accountType: "one-step",
    accountSizes: [
      {
        size: "$5k",
        registrationFee: "$49",
        verification: {
          profitTarget: "10%",
          dailyDrawdown: "3%",
          totalDrawdown: "6%",
          timeLimit: "Zero Limit",
          payout: "80/20",
          salaryPerMonth: "0.5%",
        },
        liveSimulation: {
          profitTarget: "10%",
          dailyDrawdown: "3%",
          totalDrawdown: "6%",
          timeLimit: "Zero Limit",
          payout: "14 Days",
          salaryPerMonth: "0.5%",
        },
      },
      {
        size: "$10k",
        registrationFee: "$89",
        verification: {
          profitTarget: "10%",
          dailyDrawdown: "3%",
          totalDrawdown: "6%",
          timeLimit: "Zero Limit",
          payout: "80/20",
          salaryPerMonth: "0.5%",
        },
        liveSimulation: {
          profitTarget: "10%",
          dailyDrawdown: "3%",
          totalDrawdown: "6%",
          timeLimit: "Zero Limit",
          payout: "14 Days",
          salaryPerMonth: "0.5%",
        },
      },
      {
        size: "$25k",
        registrationFee: "$180",
        verification: {
          profitTarget: "10%",
          dailyDrawdown: "3%",
          totalDrawdown: "6%",
          timeLimit: "Zero Limit",
          payout: "80/20",
          salaryPerMonth: "0.5%",
        },
        liveSimulation: {
          profitTarget: "10%",
          dailyDrawdown: "3%",
          totalDrawdown: "6%",
          timeLimit: "Zero Limit",
          payout: "14 Days",
          salaryPerMonth: "0.5%",
        },
      },
      {
        size: "$50k",
        registrationFee: "$280",
        verification: {
          profitTarget: "10%",
          dailyDrawdown: "3%",
          totalDrawdown: "6%",
          timeLimit: "Zero Limit",
          payout: "80/20",
          salaryPerMonth: "0.5%",
        },
        liveSimulation: {
          profitTarget: "10%",
          dailyDrawdown: "3%",
          totalDrawdown: "6%",
          timeLimit: "Zero Limit",
          payout: "14 Days",
          salaryPerMonth: "0.5%",
        },
      },
      {
        size: "$100k",
        registrationFee: "$450",
        verification: {
          profitTarget: "10%",
          dailyDrawdown: "3%",
          totalDrawdown: "6%",
          timeLimit: "Zero Limit",
          payout: "80/20",
          salaryPerMonth: "0.5%",
        },
        liveSimulation: {
          profitTarget: "10%",
          dailyDrawdown: "3%",
          totalDrawdown: "6%",
          timeLimit: "Zero Limit",
          payout: "14 Days",
          salaryPerMonth: "0.5%",
        },
      },
      {
        size: "$200k",
        registrationFee: "$950",
        verification: {
          profitTarget: "10%",
          dailyDrawdown: "3%",
          totalDrawdown: "6%",
          timeLimit: "Zero Limit",
          payout: "80/20",
          salaryPerMonth: "0.5%",
        },
        liveSimulation: {
          profitTarget: "10%",
          dailyDrawdown: "3%",
          totalDrawdown: "6%",
          timeLimit: "Zero Limit",
          payout: "14 Days",
          salaryPerMonth: "0.5%",
        },
      },
      {
        size: "$300k",
        registrationFee: "$1400",
        verification: {
          profitTarget: "10%",
          dailyDrawdown: "3%",
          totalDrawdown: "6%",
          timeLimit: "Zero Limit",
          payout: "80/20",
          salaryPerMonth: "0.5%",
        },
        liveSimulation: {
          profitTarget: "10%",
          dailyDrawdown: "3%",
          totalDrawdown: "6%",
          timeLimit: "Zero Limit",
          payout: "14 Days",
          salaryPerMonth: "0.5%",
        },
      },
    ],
  },
];
